CREATE TABLE IF NOT EXISTS users (
  id BINARY(16) DEFAULT (UUID_TO_BIN(UUID())),
  email VARCHAR(255) NOT NULL UNIQUE,
  fullname VARCHAR(50) NOT NULL,
  cgpa DECIMAL(2, 1) DEFAULT 0.0,
  member_since DATE NOT NULL DEFAULT (NOW()),
  hash CHAR(64) NOT NULL,
  salt CHAR(64) NOT NULL,
  PRIMARY KEY (id)
);